## Functions and Collections Data Structures

### Overview:

In this module, learners move from writing one-off Python scripts to writing reusable, organized code. The focus is on three connected ideas:

1. Functions help us package logic so we can reuse it
2. Data structures help us organize information in useful ways
3. Pandas helps us apply that logic to tabular data

By the end of the session, learners should understand not just how to write functions, but why modular code matters in real analytical work.

---

## Learning Objectives

By the end of this module, you will be able to:

- Define and call custom Python functions
- Explain the role of parameters, arguments, and return values
- Use lists, dictionaries, tuples, and sets for structured data
- Write simple validation checks inside functions
- Use Pandas inside functions for small cleaning tasks
- Refactor repetitive logic into reusable code
- Save and version reusable scripts with Git and GitHub

---

1. Why modular code matters.

As your code gets longer, copy-pasting the same logic becomes difficult to maintain. Functions solve that problem.

In [42]:
quiz_scores = [80, 90, 100]

In [43]:
quiz_average = sum(quiz_scores) / len(quiz_scores)

In [44]:
print(quiz_average)

90.0

In [45]:
exam_scores = [70, 85, 95]

In [46]:
exam_average = sum(exam_scores) / len(exam_scores)
print(exam_average)

83.33333333333333

Let's define a function so we can reuse the same code

`def` is the built-in Python keyword that tells Python we're making a function

In [47]:
def calculate_average(scores):
    average = sum(scores) / len(scores)
    return average
quiz_average = calculate_average(quiz_scores)
print(quiz_average) 
exam_average = calculate_average(exam_scores)
print(exam_average)

90.0
83.33333333333333

In [48]:
calculate_average(quiz_scores) == quiz_average

True

In [49]:
# see our function in action with our quiz and exam scores

Now the logic is written once and reused many times.

Why this matters in real work
Functions help you:

* reduce repetition
* debug more easily
* test one piece of logic at a time
* make code easier for teammates to read
* scale workflows across multiple datasets

---

A function is a reusable block of code that performs a task.

Basic Syntax:

```
def greet_user(name):
    return f"Hello, {name}!"
```

### Key Terms
* Function definition: the code that creates the function
* Parameter: a variable listed in the function definition
* Argument: the actual value passed into the function
* Return value: the output the function sends back

In [50]:
def mutiply_numbers(num1, num2):
    result = num1 * num2
    return result

In [51]:
answer = mutiply_numbers(5, 10)
answer

50

'num1' and 'num2' are parameters

5 and 10 are arguments

50 is the return value

---

## 3. Important Function Concepts

---

### A. Functions Should Usually Do One Clear Thing

In [52]:
def calculate_total(price,quantity):
    total = price * quantity
    return total

calculate_total(100,2)

200

### B. Default Parameters

If we don't specify an argument for a parameter, the default parameter is the argument

In [53]:
def power_number(base=5, exponent=2):
    result = base ** exponent
    return result

power_number(10)

100

In [54]:
power_number(10, 3)

1000

In [55]:
power_number()

#the first parameter cant be default but the second one can be. If we want to use the default value for the second parameter, we have to provide a value for the first parameter.

25

### C. Returning vs Printing

`return` sends a value back so it can be reused later.

In [56]:
def add_numbers(num1, num2):
    result = num1 + num2
    return result
x = add_numbers(5, 10)

In [57]:
def add_numbers_print(num1, num2):
    result = num1 + num2
    print(result)

    y=add_numbers_print(5, 10)

In [58]:
x

15

In [59]:
y

NameError: name 'y' is not defined

This prints the result, but does not return it for reuse.

In [ ]:
print(calculate_average(exam_scores))
calculate_average(quiz_scores)

# if i just call the function without print, it will not show the result. We have to use print to see the result of the function.
# without print it will just return quiz_score value and not exam score average

83.33333333333333

90.0

### D. Docstrings

Docstrings explain what a function does.

In [ ]:
def convert_to_upper(text):
    '''
    This function takes a string as input and 
    returns the string in uppercase.
    
    '''
    upper_text = text.upper() #built in function
    return upper_text

In [41]:
help(convert_to_upper)

Help on function convert_to_upper in module __main__:

convert_to_upper(text)
    This function takes a string as input and returns the string in uppercase.

In [60]:
def convert_to_lower(text):
    lower_text = text.lower() #built in function
    return lower_text

In [61]:
help(convert_to_lower)

Help on function convert_to_lower in module __main__:

convert_to_lower(text)

In [62]:
convert_to_upper("hello world")

'HELLO WORLD'

In [63]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

### E. Variable Scope

Variables created inside a function stay inside that function unless returned.

In [64]:
def create_greeting(name):
    greeting = f"Hello, {name}!"
    return greeting

create_greeting("Alice")

'Hello, Alice!'

In [65]:
greeting

NameError: name 'greeting' is not defined

In [ ]:
#Now greeting is defined as the result of the function create_greeting with the argument "Alice". So when we call greeting, it will return "Hello, Alice!".
greeting = create_greeting("Alice")
greeting

'Hello, Alice!'

## 4. Python Data Structures for Structured Data

Python data structures help us store and organize information.

### A. Lists

Lists store ordered, changeable collections.

In [67]:
scores = [80, 90, 100]
type(scores)

list

Use lists when:

- order matters
- items may change
- duplicates are allowed

In [68]:
first_score = scores[0] #name_of_list[index_of_thing_we_want]
first_score

80

In [69]:
second_score = scores[1]
second_score

90

In [70]:
unknown_variable = scores[5]
unknown_variable

IndexError: list index out of range

In [71]:
diffrent_data = [3,'Ritika',7.5]
type(diffrent_data)

list

In [72]:
accessing_different_data = diffrent_data[1]
accessing_different_data

'Ritika'

### B. Dictionaries

Dictionaries store key-value pairs.

Use dictionaries when:

- you want labels for values
- you want to describe records clearly

In [73]:
student = {
    "name": "Ava", #key: value, comma separates key value pairs
    "score":95,
    "passed": True
}

In [74]:
#dictionaries arent indexed like lists
#To index a dictionary we do : 
#name_of_dictionary[key_of_thing_we_want]
student[0]

KeyError: 0

In [75]:
student["name"]

'Ava'

### C. Tuples

Tuples are ordered collections that should not be changed.

Use tuples when:

- order matters
- the values should stay fixed

*Hint: Think of tuples as lists that can't be changed (immutable)*

In [80]:
#example birthdate , coordinates () 
#values that dont change are called immutable and values that can change are called mutable. Lists and dictionaries are mutable because we can change their values. Strings and tuples are immutable because we cannot change their values.

def store_birthday(month, day, year):
   
    return (month,day,year)

In [81]:
random_birthday = store_birthday(1, 1, 2000)
random_birthday

(1, 1, 2000)

In [82]:
year = random_birthday[2]
year

2000

### D. Sets

Sets store unique values.

```python
skills = {"python", "sql", "python", "excel"}
print(skills)
```

Use sets when:

- you want unique items only
- order does not matter

---

## 5. Combining Functions and Data Structures

Functions often accept data structures as inputs.

### Example: Calculate Average Score

In [83]:
def calculate_average(values):
    average = sum(values) / len(values)
    return average

calculate_average(quiz_scores)

90.0

### Example: Pull a Value from a Dictionary

In [84]:
def get_student_score(student):
    return student["score"]

get_student_score(student)

95

### Example: Work with a List of Dictionaries

```python
records = [
    {"name": "Ava", "score": 95},
    {"name": "Luis", "score": 88},
    {"name": "Mina", "score": 91}
]

In [86]:
records = [
    {"name": "Ava", "score": 95},
    {"name": "Luis", "score": 88},
    {"name": "Mina", "score": 91}
]

name = [] # empty list to store names
for record in records:
    print(name)
    print(record)

[]
{'name': 'Ava', 'score': 95}
[]
{'name': 'Luis', 'score': 88}
[]
{'name': 'Mina', 'score': 91}

In [91]:
records = [
    {"name": "Ava", "score": 95},
    {"name": "Luis", "score": 88},
    {"name": "Mina", "score": 91}
]

name = [] # empty list to store names
for record in records:
    print(name)
    print(record["name"])

[]
Ava
[]
Luis
[]
Mina

In [93]:
records = [
    {"name": "Ava", "score": 95},
    {"name": "Luis", "score": 88},
    {"name": "Mina", "score": 91}
]

name = [] # empty list to store names
for record in records:
    print(name)
    print(record["name"])
    name.append(record["name"])

[]
Ava
['Ava']
Luis
['Ava', 'Luis']
Mina

In [94]:
name

['Ava', 'Luis', 'Mina']

In [95]:
def get_names(records):
    names = []
    for record in records:
        names.append(record["name"])
    return names

get_names(records)

['Ava', 'Luis', 'Mina']

### Sidenote, you can loop over these data structures!

In [96]:
# Looping over a list
scores

[80, 90, 100]

In [97]:
for score in scores:
    print(score)

80
90
100

In [98]:
# Dictionaries require specifying which part we're looping over
student

{'name': 'Ava', 'score': 95, 'passed': True}

In [99]:
for thing in student:
    print(thing)

name
score
passed

In [ ]:
#to iterate through key-value pairs of a dict , need to call .items() on the dictionary 
for key, value in student.items():
    print(f"Key: {key}, Value: {value}")

Key: name, Value: Ava
Key: score, Value: 95
Key: passed, Value: True

---

## Sidenote 2, List Methods!

These allow us to do operations on our lists/modify them

In [2]:
numbers = [10, 20, 30]

numbers

[10, 20, 30]

In [ ]:
# .append() adds an element to the end of our list

In [ ]:
# .extend() is when you want to add multiple itmes

In [ ]:
# .insert() adds element at a specific location

In [ ]:
# .remove() removes an element from a list

In [ ]:
# .pop() removes an element at an index (and returns it), defaults to last element

In [ ]:
# .sort() will sort the values in a list!

---

## 6. Validation Inside Functions

Validation checks help catch problems early.

In [101]:
calculate_average(scores)

90.0

In [104]:
calculate_average(student)

TypeError: Input must be a list of numbers.

In [105]:
def calculate_average(values): 
    if not isinstance(values, list):
        raise TypeError("Input must be a list of numbers.")
    return sum(values) / len(values)

In [106]:
calculate_average([])

ZeroDivisionError: division by zero

In [108]:
len([])

0

In [ ]:
isinstance(student,dict)

# checks if a variable is a certain data tupe then returns true or false

True

In [110]:
help(isinstance)

Help on built-in function isinstance in module builtins:

isinstance(obj, class_or_tuple, /)
    Return whether an object is an instance of a class or of a subclass thereof.

    A tuple, as in ``isinstance(x, (A, B, ...))``, may be given as the target to
    check against. This is equivalent to ``isinstance(x, A) or isinstance(x, B)
    or ...`` etc.

In [103]:
def calculate_average(values): 
    if not isinstance(values, list):
        raise TypeError("Input must be a list of numbers.")
    if not values:
        raise ValueError("Input list cannot be empty.")
    return sum(values) / len(values)

### Why validation matters

Validation helps you:

- catch bad inputs early
- produce clearer error messages
- make functions more reliable
- prevent silent mistakes in analysis

## 7. Intro to Pandas for Function-Based Data Cleaning

Pandas is a Python library for working with tabular data.

In [111]:
# import pandas, with the alias
import pandas as pd

In [113]:
# define the dictionary
boring_dict = {
    "name": ["Ava", "Luis", "Mina", "Jordan"],
    "score": [95, None, 88, 91],
    "hours_studied": [10, 7, None, 8]
}

In [114]:
# now convert it to a dataframe
df = pd.DataFrame(boring_dict)
print(df)

     name  score  hours_studied
0     Ava   95.0           10.0
1    Luis    NaN            7.0
2    Mina   88.0            NaN
3  Jordan   91.0            8.0

In [115]:
# here are a few pandas methods to clean some data, then we'll put in a function
df.dropna() # drops rows with missing values

     name  score  hours_studied
0     Ava   95.0           10.0
3  Jordan   91.0            8.0

In [ ]:
# .dropna() drops ANY missing values from a dataframe
# BE AWARE, YOU CAN LOSE A LOT OF DATA WITH THIS
df

#df = df.dropna() # this will drop the rows with missing values and save the cleaned dataframe as df

     name  score  hours_studied
0     Ava   95.0           10.0
1    Luis    NaN            7.0
2    Mina   88.0            NaN
3  Jordan   91.0            8.0

In [ ]:
# we can fill missing values with .fillna()
#to access individual columns we can use df["column_name"]
df["score"]

0    95.0
1     NaN
2    88.0
3    91.0
Name: score, dtype: float64

In [119]:
df["score"].fillna(df["score"].mean())

# took score column , told pandas to fill in any missing data with average score

0    95.000000
1    91.333333
2    88.000000
3    91.000000
Name: score, dtype: float64

In [121]:
# Add a dervided column
df["passed"] = 0
df

     name  score  hours_studied  passed
0     Ava   95.0           10.0       0
1    Luis    NaN            7.0       0
2    Mina   88.0            NaN       0
3  Jordan   91.0            8.0       0

In [122]:
df["passed"] = df["score"] >= 70
df

     name  score  hours_studied  passed
0     Ava   95.0           10.0    True
1    Luis    NaN            7.0   False
2    Mina   88.0            NaN    True
3  Jordan   91.0            8.0    True

In [125]:
# Now we'll put them all into functions
def fill_missing_values(df):
    df["score"] = df["score"].fillna(df["score"].mean())
    return df

printdf = fill_missing_values(df)
printdf

     name      score  hours_studied  passed
0     Ava  95.000000           10.0    True
1    Luis  91.333333            7.0   False
2    Mina  88.000000            NaN    True
3  Jordan  91.000000            8.0    True

---

## 8. Refactoring Repetitive Logic

One sign that you need a function is repeated code.

*Hint*: If you catch yourself writing the same logic 3+ times, that's a good indicator to refactor into a function!

In [ ]:
# take our scores from two classes

In [ ]:
# now manually calculate the average

In [ ]:
# Now refactor into a fucntion